settingsFile: ./output/persisted/settings.json
awsResponseFile: ./output/persisted/aws-response.json

connectivityConfiguration:
  connectionTimeout: 2000
  socketTimeout: 5000

nodeStatusRetrievalConfiguration:
  forkJoinPoolSize: 32

server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./output/logs/access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /output/logs/access.%d.log.gz
        archivedFileCount: 2
        timeZone: UTC

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ./output/logs/dynamic-dashboard.log
      archive: true
      archivedLogFilenamePattern: ./output/logs/dynamic-dashboard-%d.log.gz
      archivedFileCount: 2
      timeZone: UTC
