server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /opt/broker/log/access.%d.log.gz
        archivedFileCount: 2
        timeZone: UTC

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ./logs/dynamic-dashboard.log
      archive: true
      archivedLogFilenamePattern: ./logs/dynamic-dashboard-%d.log.gz
      archivedFileCount: 2
      timeZone: UTC
